Slony: Update to 2.2.9. I also added tarball to the repo, because download fails with:
ERROR: The certificate of ‘www.slony.info’ is not trusted.
ERROR: The certificate of ‘www.slony.info’ doesn't have a known issuer.