sfcgal: Add CGAL as Requires, to solve create extension issues, like:
postgres=# create extension postgis;
ERROR: could not load library "/usr/pgsql-9.6/lib/postgis-2.3.so": libCGAL.so.11: cannot open shared object file: No such file or directory
postgres=#