gdal38: Disable libarchive support RHEL 8 as GDAL now requires at least 3.5.0. The error below is thrown on RHEL 8:
[ 29%] Building CXX object frmts/aaigrid/CMakeFiles/gdal_AAIGrid.dir/aaigriddataset.cpp.o
/git/pgrpms/rpm/redhat/main/common/gdal38/main/gdal-3.8.5-fedora/port/cpl_vsil_libarchive.cpp: In function 'archive* VSICreateArchiveHandle(const string&)':
/git/pgrpms/rpm/redhat/main/common/gdal38/main/gdal-3.8.5-fedora/port/cpl_vsil_libarchive.cpp:191:9: error: 'archive_read_support_format_rar5' was not declared in this scope
         archive_read_support_format_rar5(pArchive);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/pgrpms/rpm/redhat/main/common/gdal38/main/gdal-3.8.5-fedora/port/cpl_vsil_libarchive.cpp:191:9: note: suggested alternative: 'archive_read_support_format_rar'
         archive_read_support_format_rar5(pArchive);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         archive_read_support_format_rar