Add a linker flag for SLES. We need this, so that pgpool can find libmemched. Otherwise, we get "libmemcached.so: undefined reference to `pthread_once'" error.